### PR TITLE
unpack rogue data files into LDMX Events for single subsystems

### LINKED ISSUE #1906: unpack Rogue binary file format into LDMX Events
The Rogue binary file format is relatively simple and something we can parse. The difficulties come in the details as usual:

### What to do with the Run Control's config dump that stored in the same file?
First pass will be to just skip those "frames" (to use Rogue's vocabulary), but I can look at trying to decode the yaml and write out a separate YAML file?

### Subsystem header
Probably strip it once the we use it to determine the subsystem.

### Event building
Is it fair to assume that the events are serialized in the correct sequence? As a first pass, I'm going to assume such a thing, but we really should be checking the `timestamp` as stored in the different subsystem headers.

### EventHeader
Modify the event's EventHeader so that the event number, run number, etc are properly deduced.

### Separate `reformat` Program
https://github.com/LDMX-Software/ldmx-tb-online/tree/main/reformat the reformat program I wrote for the 2022 testbeam can be reworked to unpack all of the subsystems from one file and then attempt event alignment - i am hoping that event alignment is easier this time around since we have timestamps that come from a central place but we shall see. With my updates to Framework since 2022, I can put this reformat program into ldmx-sw now (I think).

I like the idea of having a separate `reformat` program for two reasons:
1. the stuff that `reformat` does could/would eventually be done online after event building; however, that would then implicitly require ROOT to be installed and probably ldmx-sw. The DAQ server is certainly strong/large enough to hold a container that has ldmx-sw in it. If we have some sort of "source" in ldmx-sw that can accept data via a mem-map (or similar), then we'd get the rest of ldmx-sw (including unpacking, reco, dqm filling) for "free".[0]
2. a separate program could be written to just read events until the input file runs out

The downsides of a separate `reformat` program are
1. another program to learn and know that it exists
2. will we actually move the `reformat` into online software or will it just become an intermediate step we always do
3. intermediate file duplicating data unnecessarily

[0]: The concept of a "source" is not new. Jeremy told me about it from CMSSW. The idea is that each run of ldmx-sw would have exactly one source which creates events from scratch. In order to reproduce our current behavior, we would have two sources: InputEventFile (currently handled by Framework/Process but could be refactored out), Simulator (or ReSimulator). A "source" would basically be a Producer but would _create_ the `ldmx::Event` insead of just `add`ing to it. This would allow us to restrict certain sensitive aspects of the `EventHeader` to be read-only (e.g. the event number) and open the door to other "sources" like InputRogueFile or StreamFromMMap which then feed the data downstream to the rest of the processors which remain unchanged.

### PR DESCRIPTION
**Pull request by tomeichlersmith**
I am updating _ldmx-sw_, here are the details.

- replaced `rogue-extract.py` with a `rogue-extract` C++ program that allows developers to inspect frames coming out of a Rogue file in a `hexdump`-like presentation (without needing the Rogue package)
- replaced `SingleSubsystemUnpacker` with logic that extracts frames from a Rogue file, TS example used for testing
- remove DAQ header processing from ZCCDecoder (necessary to make decoding functional again)
- Various cleanup in TS decoding code done while debugging
  - make `runReformatting_*` script an executable program (do _not_ `source` or `.` the script) and have it exit if there is an error, caught some variable mis-spellings or missing definitions
  - patch some printouts in ZCCMDecoder

### What are the issues that this addresses?
This partially resolves #1906 , I think I will close that issue and make a new one which focuses on the next staged of unpacking/decoding: supporting event alignment and mutliple subsystems.

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments.
- [x] I read, understood and follow the [coding rules](https://ldmx-software.github.io/developing/coding-rules.html).
- [x] I ran my developments and the following shows that they are successful.
```
mkdir ts-decode
cd ts-decode
# copy example data file, this one is 4.1GB
scp <SLAC DAQ Server>:/u1/eberzin/ldmx-firmware/software/data_20251208_225935_dark_current_kicker_trigger.dat .
realpath data_20251208_225935_dark_current_kicker_trigger.dat > single-file.txt
../TrigScint/util/runReformatting_ESA2025sliceTest.sh -f single-file.txt -e 1000
```
- [x] confirm decoding is operational for TS -> remove `*FixedLength` producer and `rogue-extract.py`?
- [x] add subsystem/contributor constants into `SingleSubsystemUnpacker` like is done in `rogue-extract`?

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
Clang and LTO run is failing since I have a set but unused variable in the decoder (`time_stamp`). I'm thinking about just adding it to the event header as TS-specific time stamp so its at least available for later processing.

File: TrigScint/util/runReformatting_ESA2025sliceTest.sh [hunk 1]
```diff
@@ -127,7 +123,7 @@ for file in $(cat $fileList) ; do
 	echo
 	echo "**********************************************************"
 	echo
-	echo "Done reformatting $nEvsRun events from $file in $((timeEnd-timeStart)) seconds: "
+	echo "Done reformatting $nEvents events from $file in $((timeEnd-timeStart)) seconds: "
```
Comment (bryngemark) [inline TrigScint/util/runReformatting_ESA2025sliceTest.sh]: this used to be read from a log (from an initial python parsing step needed for CERN testbeam data where firmware channel alignment was... experimental...), so `nEvsRun` would be the actual number of found events in an input file. but we can keep this printout even if it has lost its value and i just missed removing it (much like other things you have been cleaning up, thank you for this service!!)

File: TrigScint/util/runReformatting_ESA2025sliceTest.sh [hunk 2]
```diff
@@ -3,6 +3,9 @@
 # a script to run reformatting on all files in a file list
 # this is the ESA 2025 slice test data version
 
+set -o errexit
```
Comment (bryngemark) [inline TrigScint/util/runReformatting_ESA2025sliceTest.sh:6]: 🙏

**Review by bryngemark — COMMENTED** [review]
i very much like this leap forward. once TS decoding works i'd love to just see some example plots (or make them if that's easier, but the whole chain to plots should be runnable with the bash script) so we can confirm the output data quality.

**Comment by bryngemark** [comment]
a thought, once we have working encoder/decoder pairs for all subsystems, we should have a CI test running the (un)packer code. this way we can ensure robustness against format changes and i think that can save us a lot of future headache.

**Comment by tomeichlersmith** [comment]
As far as I can tell, the TS decoding is functional. The channels seem to have real PE values, but I would like @bryngemark or @EBerzin to double check.

File: Packing/src/Packing/LDMXRoRHeader.cxx [hunk 3]
```diff
@@ -4,6 +4,36 @@
...
+  { "ecal", 5 },
+  { "hcal", 5 }
+};
+
+const std::unordered_map<std::string, int> LDMXRoRHeader::CONTRIBUTOR_ID = {
+  { "tdaq", -1 },
+  { "ts", 1 },
+  { "tracker", -1 },
+  { "ecal", 20 },
+  { "hcal", 40 }
```
Comment (tvami) [inline Packing/src/Packing/LDMXRoRHeader.cxx]: I have in my notes that we had this the other way around (for most of the time) i.e. ECAL at 40 and HCAL at 20. So are we sure it's like this?

Comment (tomeichlersmith) [reply Packing/src/Packing/LDMXRoRHeader.cxx]: no, i just guessed while mocking up the code - i'll fix it

**Review by tvami — APPROVED** [review]

**Comment by tvami** [comment]
I tested with 
```
srv-esa-nw01:/u1/eberzin/ldmx-firmware/software/data_20251211_132257_track_trigger.dat
```
with is much smaller, it's 45 MB. So certainly easier to have it as an input to a future CI, which I think we should add imminently. 

As far as I can tell it works:

```
[tamasvami@sdfiana007 ldmx-sw]$ TrigScint/util/runReformatting_ESA2025sliceTest.sh -f single-file.txt -e 1000
Running over /sdf/group/ldmx/users/tamasvami/data_20251211_132257_track_trigger.dat ...
Using root file output path /sdf/group/ldmx/users/tamasvami/rootFiles
Running raw unpacking on /sdf/group/ldmx/users/tamasvami/data_20251211_132257_track_trigger.dat to produce /sdf/group/ldmx/users/tamasvami/rootFiles/data_20251211_132257_track_trigger.root ...
denv_workspace="/sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw" denv fire /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/runRawUnpackerZCCM.py /sdf/group/ldmx/users/tamasvami/data_20251211_132257_track_trigger.dat /sdf/group/ldmx/users/tamasvami/rootFiles/data_20251211_132257_track_trigger.root 1000
---- LDMXSW: Loading configuration --------
Processing 1000 events
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
[ Process ] 0  info: RunHeader { run: 1, numTries: 0, detectorName: , description: 
  intParameters: 
    RandomNumberMasterSeed[raw] = 1
  floatParameters: 
  stringParameters: 
    Pass = raw, version = v4.5.9
}
---- LDMXSW: Event processing complete  --------
denv_workspace="/sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw" denv fire /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/runZCCMDecode.py /sdf/group/ldmx/users/tamasvami/rootFiles/data_20251211_132257_track_trigger.root /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger.root raw 70 /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/../data/channelMap_4modules_14lanes.txt 2
---- LDMXSW: Loading configuration --------
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
---- LDMXSW: Event processing complete  --------
denv_workspace="/sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw" denv fire /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/runTSEventProducer.py /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger.root 0 2
---- LDMXSW: Loading configuration --------
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
---- LDMXSW: Event processing complete  --------
denv_workspace="/sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw" denv fire /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/runTestBeamHitReco.py /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger_linearize.root 32
---- LDMXSW: Loading configuration --------
using gain file /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251208_225935_dark_current_kicker_trigger_parsed_50k_linearize_gains.txt
Using this list of gains:
[2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0]
Using this list of peds:
[-2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0]
 [ TestBeamHitProducer ] In configure(), got parameters 
	 inputCollection = QIEsamplesPad1
	 inputPassName = 
	 outputCollection = testBeamHitsPad1
	 startSample = 32
	 pulseWidth = 5
	 pulseWidthLYSO = 5
	 gain[0] = 2e+06
	 nInstrumentedChannels = 24
	 doCleanHits = 0
	 pedestals[0] = -2
	 MIPresponse[0] = 1	.
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
---- LDMXSW: Event processing complete  --------
denv_workspace="/sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw" denv fire /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/runTestBeamClustering.py /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger_linearize_hits.root
---- LDMXSW: Loading configuration --------
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
---- LDMXSW: Event processing complete  --------
denv_workspace="/sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw" denv fire /sdf/group/ldmx/users/tamasvami/iss1921/ldmx-sw/TrigScint/exampleConfigs/runZCCMana.py /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger_linearize.root 0
---- LDMXSW: Loading configuration --------
Using this list of gains, from /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251208_225935_dark_current_kicker_trigger_parsed_50k_linearize_gains.txt:
[2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0, 2000000.0]
Using this list of peds:
[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
[ Process ] 0  info: Opening file /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger_linearize.root
[ Process ] 0  info: Closing file /sdf/group/ldmx/users/tamasvami/rootFiles/decoded_data_20251211_132257_track_trigger_linearize.root
---- LDMXSW: Event processing complete  --------

**********************************************************

Done reformatting 1000 events from /sdf/group/ldmx/users/tamasvami/data_20251211_132257_track_trigger.dat in 43 seconds: 
txt -> dat in 0 s, 
dat -> raw root in 5 s, 
raw root -> QIE in 5 s, 
QIE -> linear charge in 5 s.
linear charge -> testbeam hits in 6 s.
testbeam hits -> clusters in 5 s.
event analysis in 17 s.
hit analysis in 0 s.

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
```

**Comment by tvami** [comment]
> we should have a CI test running the (un)packer code.

Made an issue for this: https://github.com/LDMX-Software/ldmx-sw/issues/1940

**Comment by tvami** [comment]
> with is much smaller, it's 45 MB. So certainly easier to have it as an input to a future CI, 

I figured out what to look at after this PR, the files in the root_files are not showing much, so this .dat file is probably not what we should use to the CI

**Comment by bryngemark** [comment]
Ok, I got around to running this with the same file I had been analyzing before: `data_20251208_225935_dark_current_kicker_trigger.dat`
The two images (black plot is old python rogue parsing and single system unpacker, purple is the method from this PR) are examples from the first 2000 events and they look identical down to the stats box. Almost all distributions do. 

qs_pad1_2000events_2025dec8_kicker_oldReformat
qs_pad1_2000events_2025dec8_kicker_iss1906reformat

The one weird thing I found was that module ID goes from being wrong in one way (centered on 9040) to wrong in another way (set to some 300k?). I'm not sure we set it properly (to one of 1-4) in the TS decoding though. Same for fiber nb (which is supposed to be lane number (which in turn is not yet set)) but this is wrong in the exact same way for both methods.

I was also initially thrown off in my comparisons by the pad numbering starting at 1 again and not 0 which it was for a while. I am happy with this numbering convention though.

So I declare this workflow operational to at least the level we had before.

**Review by bryngemark — APPROVED** [review]
