### PR TITLE
Fix narrowing conversions

### LINKED ISSUE #1199: Narrowing conversion warnings by the compiler
**Describe the bug**
Inspired by the comment in https://github.com/LDMX-Software/ldmx-sw/pull/1198#issuecomment-1717288314 when I compile ldmx-sw I see the following narrowing conversions in ldmx-sw:

In `HcalGeometry.cxx`
```
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx: In member function 'void ldmx::HcalGeometry::buildStripPositionMap()':
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:156:31: warning: narrowing conversion of 'section' from 'int' to 'unsigned int' [-Wnarrowing]
  156 |         const ldmx::HcalID id{section, layer, strip};
      |                               ^~~~~~~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:156:40: warning: narrowing conversion of 'layer' from 'int' to 'unsigned int' [-Wnarrowing]
  156 |         const ldmx::HcalID id{section, layer, strip};
      |                                        ^~~~~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:156:47: warning: narrowing conversion of 'strip' from 'int' to 'unsigned int' [-Wnarrowing]
  156 |         const ldmx::HcalID id{section, layer, strip};
      |                                               ^~~~~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:211:57: warning: narrowing conversion of 'id.ldmx::HcalID::section()' from 'int' to 'unsigned int' [-Wnarrowing]
  211 |                       (getScintillatorLength({id.section(), 2, id.strip()}) -
      |                                               ~~~~~~~~~~^~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:211:72: warning: narrowing conversion of 'id.ldmx::HcalID::strip()' from 'int' to 'unsigned int' [-Wnarrowing]
  211 |                       (getScintillatorLength({id.section(), 2, id.strip()}) -
      |                                                                ~~~~~~~~^~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:238:57: warning: narrowing conversion of 'id.ldmx::HcalID::section()' from 'int' to 'unsigned int' [-Wnarrowing]
  238 |                       (getScintillatorLength({id.section(), 2, id.strip()}) -
      |                                               ~~~~~~~~~~^~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/DetDescr/src/DetDescr/HcalGeometry.cxx:238:72: warning: narrowing conversion of 'id.ldmx::HcalID::strip()' from 'int' to 'unsigned int' [-Wnarrowing]
  238 |                       (getScintillatorLength({id.section(), 2, id.strip()}) -
```

and in `HgcrocEmulator.cxx`

```
/Users/tav/Documents/1Research/LDMX/ldmx-sw/Tools/src/Tools/HgcrocEmulator.cxx: In member function 'std::vector<ldmx::HgcrocDigiCollection::Sample> ldmx::HgcrocEmulator::noiseDigi(const int&, const double&) const':
/Users/tav/Documents/1Research/LDMX/ldmx-sw/Tools/src/Tools/HgcrocEmulator.cxx:235:17: warning: narrowing conversion of 'pedestal' from 'double' to 'int' [-Wnarrowing]
  235 |     int adc_tm1{pedestal};
      |                 ^~~~~~~~
/Users/tav/Documents/1Research/LDMX/ldmx-sw/Tools/src/Tools/HgcrocEmulator.cxx:240:24: warning: narrowing conversion of '(pedestal + (((const ldmx::HgcrocEmulator*)this)->ldmx::HgcrocEmulator::noise((* & channel)) / gain)' from 'double' to 'int' [-Wnarrowing]
  240 |     int adc_t{pedestal + noise(channel)/gain};
      |               ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

I believe this second one is responsible for the msg @bryngemark referred too.

**To Reproduce**

Just compiling with the latest gcc version

### PR DESCRIPTION
**Pull request by tvami**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This resolves https://github.com/LDMX-Software/ldmx-sw/issues/1199

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments

- [x] I ran my developments and the following shows that they are successful.

The warning msg-s are gone.

- [x] I attached any sub-module related changes to this PR.

N/A

### CODE REVIEW

**Review by tomeichlersmith — APPROVED** [review]
Looks good! The runtime logs look stable and the compile time logs do not show the warnings for these anymore :)

File: DetDescr/include/DetDescr/HcalID.h [hunk 1]
```diff
@@ -73,37 +73,37 @@ class HcalID : public HcalAbstractID {
...
    */
-  int getStrip() const { return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
+  unsigned int getStrip() const { return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
 
   /**
    * Get the value of the 'strip' field from the ID.
    * @return The value of 'strip' field.
    */
-  int strip() const { return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
+  unsigned int strip() const { return (id_ >> STRIP_SHIFT) & STRIP_MASK; }
```
Comment (EinarElen) [inline DetDescr/include/DetDescr/HcalID.h:107]: I _think_ this change should be fine, integer conversions are tricky sometimes but I don't think this can go wrong with a given ID

**Review by EinarElen — APPROVED** [review]

File: DetDescr/include/DetDescr/HcalID.h (hunk 1 above)
Comment (tvami) [reply DetDescr/include/DetDescr/HcalID.h:107]: Yes, I think these always return non-negative values.
