### PR TITLE
HitData bug and extra file corruption check

### LINKED ISSUE #1933: ldmx::HitData byte corruption
**Describe the bug**
`ldmx::HitData` is causing issues when running `fire` or when trying to analyze the file with a PyROOT script. The error message is almost always the same with slight variations depending on how you're running the file, but the "too many bytes: X instead of Y" is always present, as is the StreamerInfo message. 

**To Reproduce**

Only happens on some files, not sure what causes the bug.

One such file is: `/home/jihoonyoo/LDMX/8GeV_Samples/v15_EcalPN_HannaBDT_training/v4.5.4_ecal_pn_run1212_event_sim_digi.root`
On UCSB's POD

And a basic config of just the EcalVeto is enough to produce the error
```
import LDMX.Ecal.EcalGeometry
import LDMX.Ecal.ecal_hardcoded_conditions
import LDMX.Ecal.vetos as ecal_vetos
ecal_vetos.EcalVetoProcessor.recoil_from_tracking = False # Use Scoring Plane information 
ecalVeto = ecal_vetos.EcalVetoProcessor()
p.logger.custom(ecalVeto, level = 0)

p.sequence.extend([ecalVeto])
```

**Desired behavior**

Runs smoothly without any byte corruption error messages

**Screenshots**
```
Error in <TBufferFile::CheckByteCount>: Byte count probably corrupted around buffer position 85016:
        -1859780608 for a possible maximum of -10
Error in <TBufferFile::ReadVersion>: Could not find the StreamerInfo with a checksum of 0x1075 for the class "ldmx::HitData" in /home/jihoonyoo/LDMX/8GeV_Samples/v15_EcalPN_HannaBDT_training/v4.5.4_ecal_pn_run1212_event_sim_digi.root.
Error in <TBufferFile::CheckByteCount>: object of class ldmx::HitData read too many bytes: 6 instead of -1859780608
TBufferFile::CheckByteCount:0: RuntimeWarning: ldmx::HitData::Streamer() not in sync with data on file /home/jihoonyoo/LDMX/8GeV_Samples/v15_EcalPN_HannaBDT_training/v4.5.4_ecal_pn_run1212_event_sim_digi.root, fix Streamer()
```

**Environment:**
```
denv_workspace="/home/jihoonyoo/LDMX/v4.5.4/ldmx-sw"
denv_name="ldmx-sw"
denv_image="ldmx/dev:latest"
denv_mounts="/home/vamitamas/Samples8GeV /home/jihoonyoo/LDMX "
denv_shell="/bin/bash -i"
denv_network="true"
apptainer version 1.4.5-2.el8
```

**Additional context**

### PR DESCRIPTION
**Pull request by JYoo001**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?

Possible solution to #1933. The error might emerge from files that aren't closed properly, but this is could be the source of the error.

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments.
- [x] I read, understood and follow the [coding rules](https://ldmx-software.github.io/developing/coding-rules.html).

- [x] I ran my developments and the following shows that they are successful.

### CODE REVIEW

**Comment by JYoo001** [comment]
CI Failures are from other PRs

**Review by tvami — APPROVED** [review]

File: Ecal/include/Ecal/Event/EcalTrajectoryInfo.h [hunk 1]
```diff
@@ -74,7 +74,7 @@ class EcalTrajectoryInfo {
   std::vector<XYCoords> photon_trajectory_;
   std::vector<HitData> tracking_hit_list_;
 
-  ClassDef(EcalTrajectoryInfo, 2);
+  ClassDef(EcalTrajectoryInfo, 3);
```
Comment (tomeichlersmith) [inline Ecal/include/Ecal/Event/EcalTrajectoryInfo.h:77]: Was there a previous change to this class that we did not increment the version for? Incrementing the version doesn't really cost us anything, I'm just confused on how/if this helped.

File: Framework/src/Framework/EventFile.cxx [hunk 2]
```diff
@@ -115,7 +115,7 @@ EventFile::~EventFile() {
 
 bool EventFile::isCorrupted() const {
   if (is_output_file_) return file_->IsZombie();
-  return (!tree_ or file_->IsZombie());
+  return (!tree_ or file_->IsZombie() or file_->GetNkeys() == 0);
```
Comment (tomeichlersmith) [inline Framework/src/Framework/EventFile.cxx:118]: I believe this `Nkeys` check is just making sure the ROOT file is not empty. Can you use `rootls` with the file to see if its empty?
```
denv rootls -t file.root
```

File: Ecal/include/Ecal/Event/EcalTrajectoryInfo.h (hunk 1 above)
Comment (tvami) [reply Ecal/include/Ecal/Event/EcalTrajectoryInfo.h:77]: Yes, when I did the clang-tidy's for the `Clear()` to `clear()`

File: Framework/src/Framework/EventFile.cxx (hunk 2 above)
Comment (tvami) [reply Framework/src/Framework/EventFile.cxx:118]: This is useful when ROOT does it's recovery mechanism, but cant actually recover all the keys

**Review by tomeichlersmith — APPROVED** [review]
Cool, thanks for answering my questions @tvami I think this makes sense then
